### ISSUE TITLE
TAS_Toolkit: Fix problems created by manual merge

### ISSUE THREAD

**Issue by adecler** [BHoM/TAS_Toolkit#128]
Someone has been naughty and did a manual merge 😉 . This is what might happen when you do:

![image](https://user-images.githubusercontent.com/16853390/50945004-b4761700-14cd-11e9-878e-0245591c6996.png)

![image](https://user-images.githubusercontent.com/16853390/50945039-e2f3f200-14cd-11e9-896e-b9cfc101f1b5.png)

Can you fix this?.

**Comment by adecler** [comment]
The problem of PropertyValue was fixed in https://github.com/BHoM/BHoM_UI/pull/57
Can you update your repo and check again?

**Comment by FraserGreenroyd** [comment]
This should be getting resolved in the PR for #127 as part of the larger tidy bring raised soon. Merge markers have been removed, and recompile run through the VisualStudio file. I'll make notes about testing with CodeAssistant as well in the PR to make sure it's specifically reviewed :smile:
