### ISSUE TITLE
TAS_Toolkit: SAM Template CartsionPoint Error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#156]
We need to implement protection for PolyLoop
`ERROR: The element 'PolyLoop' in namespace 'http://www.gbxml.org/schema' has incomplete content. List of possible elements expected: 'CartesianPoint' in namespace 'http://www.gbxml.org/schema'. Line Position 13 Line Number: 16102
`

[BHoMgbXML3_TAS.zip](https://github.com/BHoM/TAS_Toolkit/files/2899951/BHoMgbXML3_TAS.zip)
[TBDandDynamo.zip](https://github.com/BHoM/TAS_Toolkit/files/2900665/TBDandDynamo.zip)

**Comment by FraserGreenroyd** [comment]
Not related to TAS Toolkit. Closed.
