### ISSUE TITLE
TAS_Toolkit: missing feature list

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#161]
### TBD 
- [ ]  run sizing
`TBD.TBDDocument.sizing (0)`

- [ ]  run simulation
'tbdDoc.simulate(startDay,endDay,autoviewResult,outputaperature, outputall, merge,tsdpath,weightingfactor,hWnd)
`TBD.TBDDocument.simulate 1, 365, 0, 1, 0, 0, strPathTSD, 0, False`

- [ ]   ShowVisualisation
TBD.TBDDocument.ShowVisualisation()

- [ ]   ImportShadingData(strPath As String)
TBD.TBDDocument.ImportShadingData strPathT3D

### T3D 
this one is very limited all we need is just import gbXML, clean and update names and export to TBD
- [ ]   TAS3D.T3DDocument.ImportGBXML(gbXMLPath, 1, 1, 1);

- [ ] RemoveUnusedZones
```
                private static void RemoveUnusedZones(TAS3D.T3DDocument T3DDocument)
                {
                    List<TAS3D.Zone> aZoneList = new List<TAS3D.Zone>();

                    int aIndex = 1;
                    TAS3D.Zone aZone = T3DDocument.Building.GetZone(aIndex);
                    while (aZone != null)
                    {
                        if(aZone.isUsed == 0)
                            aZoneList.Add(aZone);
                        aIndex++;
                        aZone = T3DDocument.Building.GetZone(aIndex);
                    }

                    aZoneList.ForEach(x => x.Delete());
                }
```

- [ ] ExportT3D
here I also have ready function to adopt

**Comment by FraserGreenroyd** [comment]
As TAS API has updated since 2019, it's understood that this issue would not be solvable currently and would need re-raising against the new API if there's desire to keep the toolkit going in the future 😄
