### ISSUE TITLE
TAS_Toolkit: Importing dbl surfaces error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#165]
I just realized that when we pull model from TAS we have and push to gbXML we have dbl surfaces with doors.

See example here.. I think if we fix pull normals should work fine.

![image](https://user-images.githubusercontent.com/26113670/53790924-03658900-3f20-11e9-9c4f-c9c3d95f84c6.png)

[2019-03-05 PullTasPushgbXML.zip](https://github.com/BHoM/TAS_Toolkit/files/2929907/2019-03-05.PullTasPushgbXML.zip)

**Comment by FraserGreenroyd** [comment]
Issue closed as discovered to be a non-issue with TAS TK and rather an issue with geometry thickness.
