### ISSUE TITLE
TAS_Toolkit: Building Elements duplicated when pulled from tbd file 

### ISSUE THREAD

**Issue by mariatjader** [BHoM/TAS_Toolkit#170]
When pulling data from TAS the elements seems to go through multiple times. It was 42 building elements from the tbd file, and in BHoM 483 elements are showing up. 

![image](https://user-images.githubusercontent.com/42934052/54044688-88260080-41c7-11e9-9bb1-656b67b833cf.png)

![image](https://user-images.githubusercontent.com/42934052/54044714-9116d200-41c7-11e9-84d4-a04b99b51bf9.png)

**Comment by FraserGreenroyd** [comment]
Following review with @mariatjader this is not an issue. Closed.
