### ISSUE TITLE
TAS_Toolkit: Push Building Element

### ISSUE THREAD

**Issue by mariatjader** [BHoM/TAS_Toolkit#173]
### For Building Elements:

- [ ] Assign the right Constructions
- [ ] Add GUID 
- [ ] Add IsAir
- [ ] Add IsGround
- [ ] Add Colour
- [ ] Add Reversed

- [ ] Add Altitude
- [ ] Add AltitudeRange
- [ ] Add Inclination
- [ ] Add Orientation
- [ ] Add GValue
- [ ] Add LTValue
- [ ] Add UValue

**Comment by FraserGreenroyd** [comment]
As a tip, avoid adding any property which may be able to be calculated via an engine method (e.g. `IsGround`) as the properties which may exist today won't necessarily exist in the oM updates coming in the next few weeks :smile:

**Comment by mariatjader** [comment]
Pushing Building Elements (now Panels) handled by TBD part of TAS Toolkit. Functionality for T3D is captured in #190
