### ISSUE TITLE
TAS_Tookit: Push Calendar

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#177]
When we refer to IC we need to always set up Calendar in first step in order to make DayTypes like HDD, CDD publicHolidays etc...

this is used later on in IC on which day they should be assign
![image](https://user-images.githubusercontent.com/26113670/55716858-ebd26200-59ef-11e9-9781-031fbc7ed7dc.png)

**Comment by FraserGreenroyd** [comment]
Closed by #213
