### ISSUE TITLE
TAS_Toolkit: Push to T3D

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/TAS_Toolkit#190]
Build the convert methods to be able to convert BHoM objects into TAS T3D format so we can push T3D in the new T3D adapter.

 - [ ] Panels
 - [ ] Spaces
 - [ ] Building

**Comment by mariatjader** [comment]
Skeleton functionality included which contains the methods to begin converting to/from T3D for Building, Space, and Panels.

Building is mostly implemented, other elements need to be completed.

Adapter is set up to read building and spaces, functionality for reading panels needs adding. Functionality for push needs reviewing.

**Comment by mariatjader** [comment]
Assigning @michaldengusiak to pick up in my stead.

**Comment by FraserGreenroyd** [comment]
Solved by #173
