### ISSUE TITLE
TAS_Toolkit: Push/Pull to TCD

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#194]
simple and easy task generate and pull from Construction File
constructionRoot As ConstructionFolder
- [ ] additionalHeatTransfer As Single
- [ ] conductance As Single
- [ ] description As String
- [ ] externalBlind As Boolean
- [ ] externalEmissivity As Single
- [ ] externalSolarAbsorptanceExtSurf As Single
- [ ] externalSolarAbsorptanceIntSurf As Single
- [ ] FFactor As Single
- [ ] GUID As String
- [ ] internalBlind As Boolean
- [ ] internalEmissivity As Single
- [ ] internalSolarAbsorptanceExtSurf As Single
- [ ] internalSolarAbsorptanceIntSurf As Single
- [ ] lightReflectance As Single
- [ ] lightTransmittance As Single
- [ ] Property materialWidth(index As Long) As Single
- [ ] name As String
- [ ] solarTransmittance As Single
- [ ] timeConstant As Single
- [ ] type As ConstructionTypes
- [ ] Const tcdOpaqueConstruction = 1
- [ ] Const tcdTransparentConstruction = 2

materialRoot As MaterialFolder

- [ ] Enum MaterialProperties:
- [ ] conductivity As Single
- [ ] convectionCoefficient As Single
- [ ] density As Single
- [ ] description As String
- [ ] externalEmissivity As Single
- [ ] externalLightReflectance As Single
- [ ] externalSolarReflectance As Single
- [ ] internalEmissivity As Single
- [ ] internalLightReflectance As Single
- [ ] internalSolarReflectance As Single
- [ ] isBlind As Boolean
- [ ] lightTransmittance As Single
- [ ] name As String
- [ ] solarTransmittance As Single
- [ ] specificHeat As Single
- [ ] type As Long
- [ ] vapourDiffusionFactor As Single
- [ ] width As Single

Enum MaterialTypes Member of TCD.MaterialTypes:

- [ ] Const tcdGasLayer = 4
- [ ] Const tcdOpaqueLayer = 2
- [ ] Const tcdOpaqueMaterial = 1
- [ ] Const tcdTransparentLayer = 3

Enum SurfaceResistanceType Member of TCD.SurfaceResistanceType:

- [ ] Const tcdAshrae = 1
- [ ] Const tcdTas = 0
- [ ] Const tcdUser = 2

**Comment by mariatjader** [comment]
Reassigned following discussion with @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
As TAS API has updated since 2019, it's understood that this issue would not be solvable currently and would need re-raising against the new API if there's desire to keep the toolkit going in the future 😄
