### ISSUE TITLE
TAS_Toolkit: Macro test folder

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/TAS_Toolkit#199]
Include push and pull scripts for macro testing.

 - [x] Pull from TAS
 - [x] Push to TAS

**Comment by michaldengusiak** [comment]
@FraserGreenroyd 

[I created folders and setting up examples](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/_Macro?csf=1&e=VSrlGI)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak I will review later as in workshops now - let me know when done and I'll review and close appropriately :smile:

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  ok done

**Comment by FraserGreenroyd** [comment]
Thanks @michaldengusiak ! :smile:
