### ISSUE TITLE
TAS_Toolkit: Pull TSD warning

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#202]
can we get this fixed, seems we miss data
![image](https://user-images.githubusercontent.com/26113670/60093806-44d5aa80-9742-11e9-9ecd-501a338c828a.png)

test file [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/TAS_Toolkit/TAS_Toolkit-Issue202_PullTSD?csf=1&e=IcFFPg)

**Comment by FraserGreenroyd** [comment]
![image](https://user-images.githubusercontent.com/18049174/60182782-e03b4e00-981c-11e9-8ff8-d628bfe83c6d.png)

Cannot reproduce - try placing the component on the canvas again and selecting the enum type from the options and see if that works? :smile:
