### ISSUE TITLE
TAS_Toolkit: Pull Spaces Gain empty

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#207]
#### Description:
Gains do not load anymore after new update

![image](https://user-images.githubusercontent.com/26113670/60647935-c3af9f00-9e36-11e9-83b0-2fe90121eb1b.png)

#### How to replicate:

Run attached script

#### Test file(s):

[TestFile](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/TAS_Toolkit/TAS_Toolkit-Issue207_PullTBD?csf=1&e=0ZzO1l)

**Comment by FraserGreenroyd** [comment]
![image](https://user-images.githubusercontent.com/18049174/60660448-b6eb7500-9e4f-11e9-94d4-b341de0d90c8.png)

Gains have never been set on the Space up till now, they are accessed by querying the `InternalCondition` where `Gains` are correctly set following the changes.

See here for more information: https://github.com/BHoM/TAS_Toolkit/blob/master/TAS_Engine/Convert/Environment_oM/Space.cs

If `Gains` need to be set on the spaces please raise a feature request :smile:
