### ISSUE TITLE
TAS_Toolkit: Pull Panel allow to skip not closed geometry

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#208]
#### Description:

Currently if there is not closed polyline nothing is imported we should skip this panel or preferably imported with error so we can fix geometry in BHoM

![image](https://user-images.githubusercontent.com/26113670/60649960-08d5d000-9e3b-11e9-8760-b4e43aea31f1.png)

#### How to replicate:

Run Script

#### Test file(s):

[TestFile](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/TAS_Toolkit/TAS_Toolkit-Issue207_PullTBD?csf=1&e=0ZzO1l)

**Comment by michaldengusiak** [comment]
yes, I come across this as well during dynamo tests
![image](https://user-images.githubusercontent.com/26113670/65129782-f445b480-d9f3-11e9-8250-62e94182be56.png)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak is this issue still relevant following the changes to Geometry_Engine which now does allow the `CleanPolyline` method to run on non-closed polylines?

**Comment by FraserGreenroyd** [comment]
This has been resolved by allowing non-closed polylines to be cleaned with the `CleanPolyline` method thanks to @RasmusCanfjorden so this issue has not been seen recently. It can be reopened if further issues present :smile:
