### ISSUE TITLE
update to new Tas 9.4.5 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#232]
#### Parent issue(s) or Pull Request(s) causing the changes:

New Tas 9.4.5

#### Description:

All Tas applications have been updated from 32-bit to 64-bit. What this means is that the memory limit has been drastically improved and will allow for much bigger models to be created. This includes but is not limited to larger daylight calculations, larger thermal models and larger system models.

Evolution
The following file types have evolved since 9.4.4:
•	.T3D
•	.TAI
•	.TBD
•	.TCD
•	.TCR
•	.TIC
•	.TPD
•	.TSD
•	.TWD

3D Modeller
•	Analysis model errors and warnings: Multiple selection is now available to set the “checked” flag.
•	Movie or images showing the movement of the sun through one day now include the sun graphics if displayed in the current view.
•	IDF files and DOE INP/IN files can now be imported into Tas3D through options in the “File” menu. See sections on IDF Wizard and DOE Importer below for more details.
•	Windows style has been updated to modernised the look of the user interface.

Building Simulator (TBD)
•	TBD can now directly import weather data from EPW and TM2 files.
•	Added an option to the simulation dialog that allows previously created zone groups in TSD files to be overwritten when merging into a TSD file.
•	Windows style has been updated to modernised the look of the user interface.
•	Glazing U Values can now be calculated using ISO 15099 methodology.

Result Viewer (TSD)
•	The Performance Summary now includes buttons which when clicked will take the user to a chart displaying the selected result for the related zone and day, with a relevant output filter.
•	Windows style has been updated to modernised the look of the user interface.

Systems (TPD)
•	Plant room heating and cooling sources (Boiler, Chiller, CHP, etc.) now include losses from tanks and pipe loss components in capacity sizing (when doing so increases the sized value). Tank losses are included optionally – option is on by default.
•	Windows style has been updated to modernised the look of the user interface.

Tas Manager
•	Right-clicking a folder in the treeview and selecting “Open in Explorer” will open the folder in Windows Explorer.
•	Tas files can now be opened from the batch simulation dialog via the right-click menu.

Tas LEED Excel Plugin
A new tool to automatically complete many of the fields in a Minimum Energy Performance Calculator spreadsheet for LEED v2009 or v4. The tool is a plugin which once installed can be launched from within Microsoft Excel. A completed 90.1 project with .NPO file is required in order to run the tool.
The current version of the tool is v1.0.0.0.

IDF Wizard
•	IDF files can now be imported directly into the Tas 3D Modeller. Three types of import are now possible :
o	TBD only: All data imported directly to TBD, as in previous versions of Tas.
o	Tas3D only: Geometry, zoning, and building elements imported to Tas3D.
o	Tas3D and TBD: Geometry, zoning, and building elements imported to Tas3D, constructions, internal conditions, and feature shades imported to TBD.
•	IDF versions up to v9.1 now supported, exported IDF version is v9.1.

DOE Importer
•	INP and IN files can now be imported directly into the Tas 3D Modeller. Three types of import are now possible :
o	TBD only: All data imported directly to TBD, as in previous versions of Tas.
o	Tas3D only: Geometry, zoning, and building elements imported to Tas3D.
o	Tas3D and TBD: Geometry, zoning, and building elements imported to Tas3D, constructions, internal conditions, and feature shades imported to TBD.

Design Day Wizard
•	Heating and cooling design days can be created using the 2017 ASHRAE Weather Data.

Climate Based Daylight Modelling
•	LEED Option 2 report has been updated.
•	Tas Worker Peer tray app no longer runs on start-up by default after installing. 
•	Live search in zones filter list to make it easier to include/exclude zones.

**Comment by FraserGreenroyd** [comment]
@michaldengusiak I do not have access to a copy of TAS 9.4.5, so this would not be an issue that I could resolve I'm afraid, at least not at this time. I am happy for you to upgrade TAS_Toolkit to operate with the new version and review as appropriate if that helps your development workflows :smile:

**Comment by FraserGreenroyd** [comment]
As TAS API has updated since 2019, it's understood that this issue would not be solvable currently and would need re-raising against the new API if there's desire to keep the toolkit going in the future 😄
