### ISSUE TITLE
TAS_Toolkit: Building Element delete redundant points

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/TAS_Toolkit#86]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This issue [here](https://github.com/BHoM/BHoM_Engine/issues/983) will allow us to clean a polyline to remove redundant points. Once implemented, this issue will need to call that function to resolve the points.
